language: php

notifications:
    on_success: never
    on_failure: change

php:
    - 5.6
    - 5.3
    - 5.2
    - hhvm

env:
    # latest stable:
    - WP_VERSION=4.2 WP_MULTISITE=0
    - WP_VERSION=4.2 WP_MULTISITE=1
    # previous stable:
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=1
    # earliest supported:
    - WP_VERSION=3.5 WP_MULTISITE=0
    - WP_VERSION=3.5 WP_MULTISITE=1

matrix:
    exclude:
        # don't test 3.5 on hiphop:
        - php: hhvm
          env: WP_VERSION=3.5 WP_MULTISITE=0
        - php: hhvm
          env: WP_VERSION=3.5 WP_MULTISITE=1

install:
    - composer install

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - phpunit
